name: Release

on: workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build project
              run: cargo build --release

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: release-build
                  path: |
                      target/release/solana-copy-trade-detect

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download Ubuntu build
              uses: actions/download-artifact@v4
              with:
                  name: release-build

            - name: List files
              run: ls -la

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: latest
                  files: |
                      target/release/solana-copy-trade-detect
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
